CREATE TABLE IF NOT EXISTS users(
	id SERIAL PRIMARY KEY,
	lastname VARCHAR(255) NOT NULL,
	firstname VARCHAR(255) NOT NULL,
	email VARCHAR(255) UNIQUE,
	phone_number CHAR(9) UNIQUE,
	role VARCHAR(10) NOT NULL DEFAULT 'USER',
	town VARCHAR(255) NOT NULL,
	district VARCHAR(255) NOT NULL,
	createdAt DATE NOT NULL DEFAULT NOW(),
	updatedAt DATE
);


CREATE TABLE IF NOT EXISTS artisans(
	id SERIAL PRIMARY KEY,
	user_id INT REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
	is_certified BOOLEAN NOT NULL DEFAULT false,
	is_active BOOLEAN NOT NULL DEFAULT true	
);


CREATE TABLE IF NOT EXISTS services(
	id SERIAL PRIMARY KEY,
	service_name VARCHAR(255) NOT NULL UNIQUE
);
ALTER TABLE artisans ADD COLUMN service_id INT REFERENCES services(id) ON UPDATE CASCADE ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS missions (
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  service_id INT REFERENCES services(id) ON DELETE CASCADE ON UPDATE SET NULL,
  content TEXT NOT NULL,
  town VARCHAR(20),
  district VARCHAR(20),
  status VARCHAR(20) --EN ATTENTE, EN COURS, ANNULEE, ACHEVEE,
);




